### ISSUE TITLE
Action of operation

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-backend-ICD-test#105] opened 2020-05-14 02:26 UTC
`Updated`
To operate back-end automatically, we need some simple script to process [actions](https://docs.google.com/document/d/1c4EmETDlvAV6VSjqaimPvoHRi4FDLkGF615n5jyBc2M/edit?usp=sharing).

- [x] Load image
- [x] Animator
- [x] Cube histogram
- [x] Z Profile on cursor
- [x] Z Profile on region
- [x] Resume
- [x] Contour
- [x] Zoom out 
- [x] Zoom in

will implement by ICD command on websocket. Action starts from sending command and finishes until the message returning.
After implement, will couple these actions with a serial of process: execute a CARTA backend, run action, kill this backend, and get a report of log message. Finally, the action will run all given images and output a series of log text files.

Working on a [report](https://docs.google.com/document/d/1-G2RSOTkeKLiotgtqWdkcLlhaEwZQ6quNjIyifGbBoc/edit?usp=sharing) for these benchmarks.

**Comment by zarda** [comment] 2020-05-19 07:42
Implemented basic process in an action, will look into the issue of why some actions are unstable, where they might be failed because of timeout for a few cases.

**Comment by kswang1029** [comment] 2020-05-21 06:52
> Implemented basic process in an action, will look into the issue of why some actions are unstable, where they might be failed because of timeout for a few cases, e.g. the large images.

could you describe a bit more about those "unstable" actions? need to know the root cause.

**Comment by zarda** [comment] 2020-05-21 07:09
Sure. 
The action: zoom in & out will change the rendering size of image on canvas. To this action, while the image size is larger than 6400x6400, the running time may be as long as 10 seconds, comparing to normal condition, in which the duration is less than 2 seconds. I am trying to increase the timeout, e.g. for reading files, for preparing work, or for waiting tile data.
To action: load image can work well for large image files.
For other actions, I did not yet test them for large images. I will have further reports about these and try to address the situation.

**Comment by kswang1029** [comment] 2020-05-21 07:11
timeout should be scaled with file sizes, instead of a fixed one for _all_ file sizes I think.

**Comment by zarda** [comment] 2020-05-21 07:19
ok, will increase the timeout according to image size, which could get from FileInfoExt.

**Closed** 2020-08-27 02:34 UTC
Labels: test implementation
